title: "NuyoaH-L"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "This is a preview of jekyll-shell-theme."
github_username: NuyoaH-L
baseurl: "/"
url: "https://www.nuyoah-l.ml"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.html
  - tongji.md
  - more.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
